<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Conditinal statements</title>

    <script>
        (function () {
            console.log('Block statement');
            var x = 1;
            while (x < 3) {
                console.log(x);
                x++;
            }

            /*Conditional statements*/
            if (true) {
                console.log('Conditional statements is true');
            } else {
                console.log('Conditional statements is false');
            }
            /**/
            console.log("Switch statement");
            var fruittype = 'Mangoes';
            switch (fruittype) {
            case "Apples":
                console.log("Apples are $0.32 a pound.");
                break;
            case "Bananas":
                console.log("Bananas are $0.48 a pound.");
                break;
            case "Mangoes":
                console.log("Mangoes are $0.56 a pound.");
                break;
            default:
                console.log("Sorry, we are out of " + fruittype + ".");
            }
            /*Try - catch statement*/
            (function () {
                try {
                    console.log('Error will be loged');
                    throw "myException"; // generates an exception
                } catch (e) {
                    // statements to handle any exceptions
                    console.error('My erros in function: ', e);
                } finally {
                    console.log('finally block is executed.')
                }
            }())

            console.log('Throw custom user exception error:')

            // Create an object type UserException
            function UserException(message) {
                this.message = message;
                this.name = "UserException";
            }

            // Make the exception convert to a pretty string when used as a string
            // (e.g. by the error console)
            UserException.prototype.toString = function () {
                return this.name + ': "' + this.message + '"';
            }

            // Create an instance of the object type and throw it
            (function () {
                try {
                    throw new UserException('Value too high');
                } catch (e) {
                    console.error(e);
                }
            }());

            console.log('finally block');

            /*If the finally block returns a value, this value becomes the return value of the entire try-catch-finally production, regardless of any return statements in the try and catch blocks:*/
            function f1() {
                try {
                    console.log(0);
                    throw "bogus";
                } catch (e) {
                    console.log(1);
                    return true; // this return statement is suspended
                    // until finally block has completed
                    console.log(2); // not reachable
                } finally {
                    console.log(3);
                    return false; // overwrites the previous "return"
                    console.log(4); // not reachable
                }
                // "return false" is executed now
                console.log(5); // not reachable
            }
            f1(); // console 0, 1, 3; returns false

            /*Overwriting of return values by the finally block also applies to exceptions thrown or re-thrown inside of the catch block:*/
            function f2() {
                try {
                    throw "bogus";
                } catch (e) {
                    console.log('caught inner "bogus"');
                    throw e; // this throw statement is suspended until
                    // finally block has completed
                } finally {
                    return false; // overwrites the previous "throw"
                }
                // "return false" is executed now
            }

            try {
                f2();
            } catch (e) {
                // this is never reached because the throw inside
                // the catch is overwritten
                // by the return in finally
                console.log('caught outer "bogus"');
            }

        }())
    </script>
</head>

<body>
    <h3>Block statement</h3>
    <p>The most basic statement is a block statement that is used to group statements. The block is delimited by a pair of curly brackets:</p>
    <hr>
    <h3>Conditional statements</h3>
    <p>A conditional statement is a set of commands that executes if a specified condition is true. JavaScript supports two conditional statements: if...else and switch.</p>
    <hr>
    <h3>Falsy values</h3>
    <p>The following values evaluate to false (also known as Falsy values):</p>
    <ul>
        <li><code>false</code></li>
        <li><code>undefined</code></li>
        <li><code>null</code></li>
        <li><code>0</code></li>
        <li><code>NaN</code></li>
        <li>the empty string (<code>""</code>)</li>
    </ul>
    <hr>
    <h3>switch statement</h3>
    <p>A switch statement allows a program to evaluate an expression and attempt to match the expression's value to a case label. If a match is found, the program executes the associated statement.</p>
    <hr>
    <h3>try...catch statement</h3>
    <p>The try...catch statement marks a block of statements to try, and specifies one or more responses should an exception be thrown. If an exception is thrown, the try...catch statement catches it.</p>
    <hr>
    <h3>finally block</h3>
    <p>The finally block The finally block contains statements to execute after the try and catch blocks execute but before the statements following the try...catch statement. The finally block executes whether or not an exception is thrown. If an exception is thrown, the statements in the finally block execute even if no catch block handles the exception.</p>
    <p>If the finally block returns a value, this value becomes the return value of the entire try-catch-finally production, regardless of any return statements in the try and catch blocks:

    </p>
    <p>Overwriting of return values by the finally block also applies to exceptions thrown or re-thrown inside of the catch block</p>
    <p>finally block is guaranteed to executed.</p>
</body>

</html>
